Repository AshciR/gerousia-bot, pull requests merged in 2021-10, with the labels that each got.

#3 Add README.md
  .gitignore
  README.md
  gerousiabot/__init__.py
  gerousiabot/discord/__init__.py
  gerousiabot/discord/discord_apis.py
  gerousiabot/main.py
  gerousiabot/telegram/__init__.py
Labels: documentation

#12 Simple requests to the Discord API (Resolves #8)
  Pipfile
  Pipfile.lock
  gerousiabot/discord_apis.py
  gerousiabot/main.py
  gerousiabot/telegram_bot.py
  tests/test_discord_apis.py
  tests/test_telegram_bot.py
Labels: enhancement

#15 Fixed Keyboard Buttons
  .gitignore
  gerousiabot/bot_handlers.py
  gerousiabot/telegram_bot.py
  gerousiabot/utils.py
  tests/test_bot_handlers.py
  tests/test_telegram_bot.py
  tests/test_utils.py
Labels: bug
